[general]
import = [
	"~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
]

[window]
title = "Qué mirás, bobo?"
dynamic_title = false
opacity = 0.85

dynamic_padding = true
decorations = "Full"

[font]
size = 16
builtin_box_drawing = true

[colors.primary]
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.cursor]
text = "CellBackground"
cursor = "#ff0000"

[font.normal]
family = "Fira Code" # "IBM Plex Mono"
style = "Reqular"


